### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by tobyzerner** [jrmajor/fluent-php#1]
Thanks for your work on this @jrmajor!

I noticed both this package and laravel-fluent are missing a LICENSE file? MIT is specified in composer.json but I think it would be good to make it explicit.

**Comment by jrmajor** [comment]
I've added license file to both packages (jrmajor/fluent-php@065fe4a36728892fe870cc802e99d77912312f30 and jrmajor/laravel-fluent@0e660721b4ae3e9109cf6b5c04b2894b4731122c).

**Comment by tobyzerner** [comment]
Thank you!
