### ISSUE TITLE
Increadibly slow on large files / quadratic runtime of parser

### ISSUE THREAD

**Issue by vodik** [jrmajor/fluent-php#8]
I tried to load a ~900KB fluent file and it took over 30 seconds to process, killing my page before it rendered anything. It specifically aborted on `return mb_substr($this->string, $offset, 1) === "\r"` in `charAtOffsetIsCrLf`

Switching from `mb_*` to the non multi-byte aware versions of these functions dramatically improved performance.

I think the parser is accidentally quadratic: `mb_substr` has to scan from the start of the string to find both the start and end position and it seems to be used extensively to check letters one at a time. The longer the file, the slower functions like `next` and `peek` will take.

**Comment by vodik** [comment]
Let me try and see if I can reproduce this on master. I see you've done a lot of work.

**Comment by jrmajor** [comment]
Thank you for reporting, can you share the `.ftl` file that caused the issue?

**Comment by vodik** [comment]
The file in question contains sensitive content I wouldn't be able to share freely. However it is machine generated - let me see if I can produce an equivalent but censored version of the file.

**Comment by vodik** [comment]
Try this: https://gist.github.com/vodik/b4aefbc78674f3f8a1b7d87d924b31b6

**Comment by vodik** [comment]
Amazing! Thank you very much.
